GET http://localhost:5000 HTTP/1.1

###

GET http://localhost:5000/user HTTP/1.1

###

GET http://localhost:5000/user/user1@mail.com HTTP/1.1

###

POST http://localhost:5000/user HTTP/1.1
content-type: application/json

{
  "name": "user 2",
  "email": "user2@mail.com",
  "address": "2st Usr"
}

###

PUT http://localhost:5000/user HTTP/1.1
content-type: application/json

{
  "name": "user 3",
  "email": "user2@mail.com",
  "address": "3st Usr"
}

###

DELETE  http://localhost:5000/user HTTP/1.1
content-type: application/json

{
  "email": "user1@mail.com"
}
